// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'invalidPlug': string;
  'notes': string;
  'orGroup': string;
  'plugColumn': string;
  'roll': string;
  'rollGrid': string;
  'rollGroup': string;
  'subtitle': string;
}
export const cssExports: CssExports;
export = cssExports;
